### ISSUE TITLE
Ángel, testigo y adorador

### ISSUE THREAD

**Issue by dbssdb** [Darkhogg/werebot#6]
Te dejo aquí estos tres por si los ves útiles en un futuro ;)

Ángel de la Guarda: Bendecido por poderes divinos, este personaje tiene la capacidad de proteger a quien crea necesario del ataque nocturno de los hombres-lobo. Dada su bondad, sin embargo, se verá forzado a cambiar de protegido cada noche, para repartir su bendición por todos los posibles inocentes, renunciando siempre a protegerse a sí mismo.
El Ángel de la Guarda no puede proteger de la decisión de los aldeanos, por lo cual el protegido puede ser linchado por la muchedumbre pese a la bendición.

Testigo: Tildado de temerario y llevado por la curiosidad, este personaje no puede resistir la tentación de intentar averiguar quienes son los hombres-lobo. Por ello, tiene un 25% de posibilidades de averiguar la identidad de uno de los hombres-lobo.
A su vez, y para su desgracia, intentar averiguar esta información hace que los lobos que sufran el espionaje esa noche tengan un 50% de posibilidades de descubrir al espía, independientemente de si el espía logra descubrirlos a ellos o no.

Adorador: Este personaje está obsesionado con los hombres-lobo, idolatrándolos como a dioses, intentando conseguir contactar con ellos y creyendo que sus fauces son la más digna de las muertes. 
No tienen ningún poder especial, salvo que desde el comienzo conoce la identidad de los dos Lobos.
Por desgracia, los lobos no le conocen a él ni tienen forma de identificarlo... Por lo cual la vida el Adorador es difícil y arriesgada.
Pese a todo, su mayor interés es conseguir sobrevivir a la masacre junto a sus adoradas bestias, haciendo todo lo posible por procurarles la victoria.

**Comment by Darkhogg** [comment]
Voy a separar esto en 3 para tener más granularidad al hacer cambios en el código. Y de paso lo pongo en inglés que lo prefiero.

**Comment by Darkhogg** [comment]
Dejo fuera al adorador: No me gustan nada los personajes que ganan por su cuenta y crean nuevos bandos, para mí este juego tiene gracia si gana o el bando lobo o el bando ciudadano, punto.
