### ISSUE TITLE
Character: The Spy

### ISSUE THREAD

**Issue by Darkhogg** [Darkhogg/werebot#8]
The Spy is a well trained, retired government spy that might use its abilities at night to try and gain knowledge about the wolves identities. Every night he uses its abilities, he has a 25% chance of finding the identity of a werewolf. However, werewolves are better than humans at stealth, and might know someone's after them. That's why, if the spies goes on to spy, there's a 50% chance the wolves find out about it and kill the spy, *whether the spy finds out who they are or not*.

(Originally suggested in #6)

---

+ The Spy must be able to issue a command at night to indicate if he wants to spy. Maybe **!spy yes** or **!spy no**? (Of course, assummed no if the night ends via timeout)
+ When spying, the spy has a 50% chance of being discovered and dying.
+ If the spy is not discovered, then there's a 25% chance of finding out the name of one werewolf. The same name should not be given out twice.
+ After finding out the names of all werewolves, the spy's ability becomes useless, so the game proceeds without asking the spy to spy. (i.e., it's assumed it chooses not to spy).

**Comment by Darkhogg** [comment]
I'm not really sure about this: the numbers seem off and it's *too random* for my taste.
Maybe if and when I implement optional, configurable characters, but not generally available.

**Comment by dbssdb** [comment]
Yes, I also believed that it was kind of weird because of the numbers but we tried it a few times and it worked. In any case it can be an idea for an alternative character in the future.

**Comment by Darkhogg** [comment]
Well, it's kind of easy to implement, so I'll just do it and add it as a possibility. It's not prioritary though.
